version: "3"
  
networks:
  default:
    name: coinguard-dev
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.9.0/24

volumes:
  postgres_data:
  user_data:

services:
  main:
    profiles: ["full"]
    privileged: true
    image: "firepandalabs.azurecr.io/coinguard/dev:latest"
    build:
      context: "."
    container_name: "coinguard-dev"
    command: tail -f /dev/null
    stop_signal: SIGINT

    depends_on:
      - postgres
      - redis

    volumes:
      - "user_data:/home/firepanda/"
      - "${PWD}:/home/firepanda/workspace"

    ports:
      - 3448:3448
      - 3449:3449

    environment:
      - ENVIRONMENT=dev

  postgres:
    image: postgres:13
    command: postgres -c config_file=/etc/postgresql.conf
    restart: always
    stop_signal: SIGINT
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=coinguard
      - POSTGRES_USER=coinguard
      - POSTGRES_PASSWORD=coinguard
    volumes:
      - ./assets/postgresql.conf:/etc/postgresql.conf
      - ./assets/postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    hostname: "redis"
    restart: always